cmake_minimum_required(VERSION 3.24)
project(wiremic LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

option(WIREMIC_BUILD_TESTS "Build unit tests" ON)

if(WIREMIC_BUILD_TESTS)
    enable_testing()
endif()

add_subdirectory(shared)
add_subdirectory(linux-app)
